version: "3.6"

networks:
  app:
    external: false
    name: ${PROJECT_NAME}_default

services:
  whoami:
    image: jwilder/whoami
    container_name: ${PROJECT_NAME}_whoami
    networks:
      - app
