version: '3.1'
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/html:/usr/share/nginx/html
      - ./data/dhparam:/etc/nginx/dhparam
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/vhost:/etc/nginx/vhost.d:rw
      - ./data/conf:/etc/nginx/conf.d
      - ./data/htpasswd:/etc/nginx/htpasswd

  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-le
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/html:/usr/share/nginx/html
      - ./data/dhparam:/etc/nginx/dhparam
      - ./data/certs:/etc/nginx/certs:rw
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/conf:/etc/nginx/conf.d
